# Generated by Django 4.2.3 on 2023-08-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='purpose',
            field=models.CharField(blank=True, choices=[('gain_weight', 'Gaining Weight'), ('lose_weight', 'Losing Weight'), ('maintain_weight', 'Maintaining Weight')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chef',
            name='purpose',
            field=models.CharField(blank=True, choices=[('gain_weight', 'Gaining Weight'), ('lose_weight', 'Losing Weight'), ('maintain_weight', 'Maintaining Weight')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='other',
            name='purpose',
            field=models.CharField(blank=True, choices=[('gain_weight', 'Gaining Weight'), ('lose_weight', 'Losing Weight'), ('maintain_weight', 'Maintaining Weight')], max_length=100, null=True),
        ),
    ]
