# Generated by Django 4.2.3 on 2023-08-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_athlete_purpose_alter_chef_purpose_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='image',
        ),
        migrations.RemoveField(
            model_name='chef',
            name='image',
        ),
        migrations.RemoveField(
            model_name='other',
            name='image',
        ),
        migrations.AddField(
            model_name='athlete',
            name='calories_should_taken',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='calories_should_taken',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='other',
            name='calories_should_taken',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
