# Generated by Django 4.2.3 on 2023-08-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_athlete_image_remove_chef_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='calories_should_taken',
        ),
        migrations.RemoveField(
            model_name='chef',
            name='calories_should_taken',
        ),
        migrations.RemoveField(
            model_name='other',
            name='calories_should_taken',
        ),
    ]
