# Generated by Django 4.2.3 on 2023-08-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_athlete_calories_should_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='water_goal',
            field=models.PositiveIntegerField(blank=True, default=8, null=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='water_goal',
            field=models.PositiveIntegerField(blank=True, default=8, null=True),
        ),
        migrations.AddField(
            model_name='other',
            name='water_goal',
            field=models.PositiveIntegerField(blank=True, default=8, null=True),
        ),
    ]
