# Generated by Django 4.2.3 on 2023-08-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletesQuotesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athletequote',
            name='content',
        ),
        migrations.RemoveField(
            model_name='athletequote',
            name='title',
        ),
        migrations.AddField(
            model_name='athletequote',
            name='inspiration',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
