# Generated by Django 4.2.3 on 2023-08-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionsandAnswers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='reciever',
        ),
        migrations.AddField(
            model_name='question',
            name='recievers',
            field=models.CharField(choices=[('athlete', 'Athletes'), ('chef', 'Chefs'), ('other', 'Others')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
