# Generated by Django 4.2.3 on 2023-08-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryApp', '0002_alter_waterentry_glasses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
