# Generated by Django 4.2.3 on 2023-08-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietApp', '0003_delete_stepsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(max_length=150),
        ),
    ]
