# Generated by Django 4.2.3 on 2023-08-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietApp', '0004_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='content',
            new_name='instructions',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(max_length=250),
        ),
    ]
