# Generated by Django 4.2.3 on 2023-08-17 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_athlete_water_goal_remove_chef_water_goal_and_more'),
        ('dietApp', '0005_rename_content_recipe_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.chef'),
        ),
    ]
